### ISSUE TITLE
차트 데이터 관련 (services/health.ts)

### ISSUE THREAD

**Issue by in3166** [POB-Frontend-4th-6team/WOB-moadata-assignment#6]
### 1. 오늘 걸음 수 중에 음수가 나오는 경우가 있습니다.

  - `/jsons/steprate/steprate_328.json`
  - 각 시간의 걸음수를 이전 10분 전의 걸음수로 빼서 나타내고 있는데 아래 처럼 음수가 나오는 경우가 한 번 존재합니다.
  - json 데이터를 바꿔줘야 할지, 아님 걸음수를 계산해주지 않고 그냥 써야할지 고민이네요.
  
![380](https://user-images.githubusercontent.com/45654988/171318168-aa31a8ea-a87f-47c8-b191-a7b15e5e3e9a.PNG)

<img src="https://user-images.githubusercontent.com/45654988/171318166-29b55b30-8b6a-46e0-a36a-63e10443bef8.PNG" width="500" />
<br>

### 2. 전체 데이터 가져오기 분리
- 아래 사진처럼 `getPeriodRateData` 안에서 `dateList`가 빈 배열일 때 전체로 보는게 나을지
- 아니면 ~`getAllHeartRateData`~ `getAllRateData` 처럼 분리하는게 나을지 의견 부탁드려요!

![get](https://user-images.githubusercontent.com/45654988/171318941-63803610-6525-4347-81f0-9df25b120f9d.PNG)

**Comment by majih93** [comment]
1번 이슈는 json 데이터를 임의로 바꿔서 하는게 낫지 않을까 싶습니다 ㅎㅎ

**Comment by markyul** [comment]
2번 이슈는 위 함수처럼 가능하면 그게 더 코드가 짧아질거 같네요

**Comment by in3166** [comment]
네 감사합니다! 그럼 말씀처럼 수정하고 푸시할게요!
